version: '3.4'

services:

  ofbiz:
    container_name: ofbiz
    build:
      context: .
      dockerfile: Dockerfile-dev
    restart: unless-stopped
    ports:
      - "8443:8443"
      - "4567:4567"  # sparkle for REST api
    volumes:
      - ./:/ofbiz  # Volume mount to allow runtime changes to xml etc.