version: '3.7'

services:
  ofbiz:
    container_name: ofbiz-api
    build:
      context: .
    restart: unless-stopped
    volumes:
      - ./:/ofbiz  # Volume mount to allow runtime changes to xml etc.
    networks:
      - ofbiz-api-network

networks:
  ofbiz-api-network:
    name: ofbiz-api-network
    driver: bridge